version: '3.4'

services: 
  middleware:
    build: ./middleware
    volumes: 
      - ./middleware:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
    expose:
      - 5000
    ports:
      - 5000:5000